version: "3"
services:
  wordpress:
    image: wordpress:php7.1-apache
    ports:
      - 8080:80
    networks:
      - common
    depends_on:
      - dbcluster
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      WORDPRESS_DB_HOST: "dbcluster"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "wordpress"
  dbcluster:
    image: toughiq/mariadb-cluster
    networks:
      - common
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    environment:
      DB_SERVICE_NAME: dbcluster 
      MYSQL_ROOT_PASSWORD: wordpress 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wordpress 
      MYSQL_PASSWORD: wordpress 

networks:
  common:
