version: '3.7'

services:
   db:
     image: mysql:5.7
     hostname: mysql
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     # dns: 172.17.0.2
     ports:
       - 3306:3306
     environment:
       SERVICE_3306_NAME: mysql 
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
    
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     dns: 172.17.0.2 # if consul agent expose 53 on 53, use ip in (ifconfig docker0), otherwise use IP of agent itself
     dns_search: service.DC1.consul
     environment:
       SERVICE_80_NAME: wordpress  
       # mysql.service.DC1.consul (DC1 = datacenter name)
       WORDPRESS_DB_HOST: mysql:3306 # should match SERVICE_3306_NAME which registred in Consul 
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}
